service: aws-python-librosa-example
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8

functions:
  hello:
    handler: handler.hello
#    layers:
#      - Ref: PythonRequirementsLambdaLayer
    events:
      - httpApi:
          path: /
          method: get

plugins:
  - serverless-python-requirements
	
custom:
  pythonRequirements:
    dockerizePip: 'non-linux'
    slim: true
    strip: false
    slimPatterns:
      - '**/test*'
    zip: true

package:
  exclude:
    - '.venv/**'
